import { contextBridge, ipcRenderer } from "electron";
import type {
  ActivityHistoryItem,
  AppUser,
  Client,
  ClientDraft,
  CybercafeSale,
  CybercafeSaleDraft,
  CybercafeTariff,
  CybercafeTariffDraft,
  CloudDesktopSessionDraft,
  DashboardMetrics,
  ExpenseDraft,
  ExpenseItem,
  InvoiceSeriesInfo,
  LoginDraft,
  PasswordChangeDraft,
  Product,
  ProductDraft,
  ReplenishmentImportSummary,
  SaleDetail,
  SaleDraft,
  SaleRecord,
  Service,
  ServiceDraft,
  SyncSnapshot,
  SyncStatus,
  StockRow,
  SupplyHistoryItem,
  UserDraft,
  UserRole,
} from "../src/types";

contextBridge.exposeInMainWorld("desktopApi", {
  getPlatform: () => process.platform,
  listProducts: (): Promise<Product[]> => ipcRenderer.invoke("inventory:list"),
  saveProduct: (draft: ProductDraft): Promise<Product[]> => ipcRenderer.invoke("inventory:save", draft),
  deleteProduct: (id: number): Promise<Product[]> => ipcRenderer.invoke("inventory:delete", id),
  listServices: (): Promise<Service[]> => ipcRenderer.invoke("services:list"),
  saveService: (draft: ServiceDraft): Promise<Service[]> => ipcRenderer.invoke("services:save", draft),
  listCybercafeTariffs: (): Promise<CybercafeTariff[]> => ipcRenderer.invoke("cybercafe:tariffs:list"),
  saveCybercafeTariff: (draft: CybercafeTariffDraft): Promise<CybercafeTariff[]> => ipcRenderer.invoke("cybercafe:tariffs:save", draft),
  listCybercafeSales: (): Promise<CybercafeSale[]> => ipcRenderer.invoke("cybercafe:sales:list"),
  createCybercafeSale: (draft: CybercafeSaleDraft): Promise<CybercafeSale[]> => ipcRenderer.invoke("cybercafe:sales:create", draft),
  listSales: (): Promise<SaleRecord[]> => ipcRenderer.invoke("sales:list"),
  createSale: (draft: SaleDraft): Promise<SaleRecord[]> => ipcRenderer.invoke("sales:create", draft),
  getSaleDetail: (saleId: number): Promise<SaleDetail | null> => ipcRenderer.invoke("sales:detail", saleId),
  printSaleInvoice: (saleId: number): Promise<boolean> => ipcRenderer.invoke("sales:print", saleId),
  exportSalePdf: (saleId: number): Promise<string | null> => ipcRenderer.invoke("sales:export-pdf", saleId),
  printSaleReceipt: (saleId: number): Promise<boolean> => ipcRenderer.invoke("sales:print-receipt", saleId),
  exportSaleReceiptPdf: (saleId: number): Promise<string | null> => ipcRenderer.invoke("sales:export-receipt-pdf", saleId),
  exportExpenseReportPdf: (html: string, fileName: string): Promise<string | null> =>
    ipcRenderer.invoke("reports:export-expense-pdf", html, fileName),
  exportReplenishmentTemplateCsv: (): Promise<string | null> => ipcRenderer.invoke("replenishments:template-export"),
  exportReplenishmentHistoryCsv: (): Promise<string | null> => ipcRenderer.invoke("replenishments:history-export"),
  importReplenishmentCsv: (): Promise<ReplenishmentImportSummary | null> => ipcRenderer.invoke("replenishments:import"),
  getSupplyHistory: (): Promise<SupplyHistoryItem[]> => ipcRenderer.invoke("history:supply"),
  getActivityHistory: (): Promise<ActivityHistoryItem[]> => ipcRenderer.invoke("history:activity"),
  pruneActivityHistory: (months: number): Promise<number> => ipcRenderer.invoke("history:prune", months),
  listExpenses: (): Promise<ExpenseItem[]> => ipcRenderer.invoke("expenses:list"),
  saveExpense: (draft: ExpenseDraft): Promise<ExpenseItem[]> => ipcRenderer.invoke("expenses:save", draft),
  getDashboardMetrics: (): Promise<DashboardMetrics> => ipcRenderer.invoke("dashboard:metrics"),
  listClients: (): Promise<Client[]> => ipcRenderer.invoke("clients:list"),
  saveClient: (draft: ClientDraft): Promise<Client[]> => ipcRenderer.invoke("clients:save", draft),
  deleteClient: (id: number): Promise<Client[]> => ipcRenderer.invoke("clients:delete", id),
  listUsers: (): Promise<AppUser[]> => ipcRenderer.invoke("users:list"),
  saveUser: (draft: UserDraft): Promise<AppUser[]> => ipcRenderer.invoke("users:save", draft),
  linkCloudUserProfile: (draft: CloudDesktopSessionDraft): Promise<AppUser[]> =>
    ipcRenderer.invoke("users:link-cloud-profile", draft),
  authenticateUser: (draft: LoginDraft): Promise<AppUser | null> => ipcRenderer.invoke("users:authenticate", draft),
  cacheCloudAuthenticatedUser: (draft: CloudDesktopSessionDraft): Promise<AppUser> =>
    ipcRenderer.invoke("users:cache-cloud-auth", draft),
  getCurrentSyncCredentials: () => ipcRenderer.invoke("users:get-sync-credentials"),
  restoreUserSession: (userId: number): Promise<AppUser | null> => ipcRenderer.invoke("users:restore-session", userId),
  logoutUser: (): Promise<void> => ipcRenderer.invoke("users:logout"),
  changeUserPassword: (draft: PasswordChangeDraft): Promise<AppUser[]> =>
    ipcRenderer.invoke("users:change-password", draft),
  setUserActive: (userId: number, active: boolean): Promise<AppUser[]> =>
    ipcRenderer.invoke("users:set-active", userId, active),
  updateUserRole: (userId: number, role: UserRole): Promise<AppUser[]> =>
    ipcRenderer.invoke("users:update-role", userId, role),
  refreshUserAccess: (userId: number): Promise<AppUser[]> => ipcRenderer.invoke("users:refresh-access", userId),
  deleteUser: (userId: number): Promise<AppUser[]> => ipcRenderer.invoke("users:delete", userId),
  getCurrentStock: (): Promise<StockRow[]> => ipcRenderer.invoke("stock:current"),
  getInvoiceSeriesInfo: (): Promise<InvoiceSeriesInfo> => ipcRenderer.invoke("sales:invoice-series"),
  advanceInvoiceSeries: (): Promise<InvoiceSeriesInfo> => ipcRenderer.invoke("sales:advance-series"),
  resetInventoryCycle: (): Promise<void> => ipcRenderer.invoke("inventory:reset-cycle"),
  getSyncStatus: (): Promise<SyncStatus> => ipcRenderer.invoke("sync:status"),
  getPendingSyncOverview: () => ipcRenderer.invoke("sync:pending-overview"),
  exportSyncSnapshot: (): Promise<SyncSnapshot> => ipcRenderer.invoke("sync:snapshot"),
  importSyncSnapshot: (snapshot: SyncSnapshot): Promise<void> => ipcRenderer.invoke("sync:import", snapshot),
  markSyncComplete: (syncedAt?: string | null): Promise<void> => ipcRenderer.invoke("sync:complete", syncedAt),
  markSyncBucketsComplete: (tables: string[], syncedAt?: string | null): Promise<void> =>
    ipcRenderer.invoke("sync:complete-buckets", tables, syncedAt),
  createBackup: (): Promise<string | null> => ipcRenderer.invoke("backup:create"),
  restoreBackup: (): Promise<string | null> => ipcRenderer.invoke("backup:restore"),
});
