-- Module Cybercafe: tarifs de connexion et recettes journalieres.
-- Executez ce fichier une seule fois dans Supabase > SQL Editor.

create table if not exists public.cybercafe_tariffs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  unit_price numeric(12, 2) not null check (unit_price > 0),
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.cybercafe_sales (
  id bigint generated by default as identity primary key,
  tariff_id bigint not null references public.cybercafe_tariffs(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price > 0),
  total_amount numeric(12, 2) not null check (total_amount > 0),
  sold_at timestamptz not null default timezone('utc', now()),
  payment_method text not null default 'Especes',
  note text,
  user_id bigint references public.users(id) on delete set null
);

alter table public.cybercafe_tariffs enable row level security;
alter table public.cybercafe_sales enable row level security;

drop trigger if exists cybercafe_tariffs_set_updated_at on public.cybercafe_tariffs;
create trigger cybercafe_tariffs_set_updated_at
before update on public.cybercafe_tariffs
for each row execute function public.set_updated_at();

drop policy if exists cybercafe_tariffs_select_policy on public.cybercafe_tariffs;
drop policy if exists cybercafe_tariffs_write_policy on public.cybercafe_tariffs;
drop policy if exists cybercafe_sales_select_policy on public.cybercafe_sales;
drop policy if exists cybercafe_sales_write_policy on public.cybercafe_sales;

create policy cybercafe_tariffs_select_policy on public.cybercafe_tariffs
for select to authenticated using (true);

create policy cybercafe_tariffs_write_policy on public.cybercafe_tariffs
for all to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy cybercafe_sales_select_policy on public.cybercafe_sales
for select to authenticated using (true);

create policy cybercafe_sales_write_policy on public.cybercafe_sales
for all to authenticated
using (true)
with check (true);

create index if not exists idx_cybercafe_sales_date on public.cybercafe_sales(sold_at desc);

create or replace function public.sync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), true);
  perform setval(pg_get_serial_sequence('public.clients', 'id'), coalesce((select max(id) from public.clients), 1), true);
  perform setval(pg_get_serial_sequence('public.expenses', 'id'), coalesce((select max(id) from public.expenses), 1), true);
  perform setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1), true);
  perform setval(pg_get_serial_sequence('public.services', 'id'), coalesce((select max(id) from public.services), 1), true);
  perform setval(pg_get_serial_sequence('public.cybercafe_tariffs', 'id'), coalesce((select max(id) from public.cybercafe_tariffs), 1), true);
  perform setval(pg_get_serial_sequence('public.cybercafe_sales', 'id'), coalesce((select max(id) from public.cybercafe_sales), 1), true);
  perform setval(pg_get_serial_sequence('public.initial_stocks', 'id'), coalesce((select max(id) from public.initial_stocks), 1), true);
  perform setval(pg_get_serial_sequence('public.replenishments', 'id'), coalesce((select max(id) from public.replenishments), 1), true);
  perform setval(pg_get_serial_sequence('public.sales', 'id'), coalesce((select max(id) from public.sales), 1), true);
  perform setval(pg_get_serial_sequence('public.sale_items', 'id'), coalesce((select max(id) from public.sale_items), 1), true);
  perform setval(pg_get_serial_sequence('public.sale_service_items', 'id'), coalesce((select max(id) from public.sale_service_items), 1), true);
  perform setval(pg_get_serial_sequence('public.stock_movements', 'id'), coalesce((select max(id) from public.stock_movements), 1), true);
  perform setval(pg_get_serial_sequence('public.audit_logs', 'id'), coalesce((select max(id) from public.audit_logs), 1), true);
  perform setval(pg_get_serial_sequence('public.inventory_cycles', 'id'), coalesce((select max(id) from public.inventory_cycles), 1), true);
end;
$$;

grant execute on function public.sync_identity_sequences() to authenticated;
