create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  username text not null unique,
  email text unique,
  password_hash text,
  role text not null check (role in ('Administrateur', 'Super admin', 'Employe')),
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  last_login_at timestamptz
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  address text,
  email text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  category text not null default 'General',
  purchase_price numeric(12, 2) not null,
  selling_price numeric(12, 2) not null,
  unit text not null default 'piece',
  alert_threshold integer not null default 0,
  supplier text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.initial_stocks (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null,
  purchase_price numeric(12, 2) not null,
  stock_date timestamptz not null default timezone('utc', now()),
  cycle_id bigint,
  user_id bigint references public.users(id) on delete set null,
  note text
);

create table if not exists public.replenishments (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null,
  purchase_price numeric(12, 2) not null,
  supplier text not null,
  replenished_at timestamptz not null default timezone('utc', now()),
  cycle_id bigint,
  user_id bigint references public.users(id) on delete set null,
  note text
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  client_id bigint references public.clients(id) on delete set null,
  sold_at timestamptz not null default timezone('utc', now()),
  total_amount numeric(12, 2) not null default 0,
  payment_method text not null default 'Especes',
  cycle_id bigint,
  user_id bigint references public.users(id) on delete set null
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null,
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2) not null
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  movement_type text not null check (movement_type in ('stock_initial', 'reapprovisionnement', 'vente')),
  quantity integer not null,
  source_table text not null,
  source_id bigint,
  movement_date timestamptz not null default timezone('utc', now()),
  cycle_id bigint,
  user_id bigint references public.users(id) on delete set null
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action text not null,
  target_table text not null,
  target_id bigint,
  details text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invoice_sequences (
  id bigint primary key,
  current_year integer not null,
  series_index integer not null default 0,
  next_number integer not null default 1,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_cycles (
  id bigint generated by default as identity primary key,
  label text not null,
  started_at timestamptz not null default timezone('utc', now()),
  user_id bigint references public.users(id) on delete set null
);

drop view if exists public.current_stock_view;

create view public.current_stock_view as
select
  p.id as product_id,
  p.name as product_name,
  coalesce(sum(case when sm.quantity > 0 then sm.quantity else 0 end), 0) as quantity_in,
  coalesce(sum(case when sm.quantity < 0 then abs(sm.quantity) else 0 end), 0) as quantity_out,
  coalesce(sum(sm.quantity), 0) as current_stock,
  p.alert_threshold as alert_threshold
from public.products p
left join public.stock_movements sm on sm.product_id = p.id
  and sm.cycle_id = (select coalesce(max(ic.id), 1) from public.inventory_cycles ic)
group by p.id, p.name, p.alert_threshold;

drop trigger if exists products_set_updated_at on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

create index if not exists idx_clients_name on public.clients(name);
create index if not exists idx_products_name on public.products(name);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_sales_sold_at on public.sales(sold_at desc);
create index if not exists idx_sale_items_sale_id on public.sale_items(sale_id);
create index if not exists idx_stock_movements_product_id on public.stock_movements(product_id);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);

alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.products enable row level security;
alter table public.initial_stocks enable row level security;
alter table public.replenishments enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.audit_logs enable row level security;
alter table public.invoice_sequences enable row level security;
alter table public.inventory_cycles enable row level security;

drop policy if exists users_read_all on public.users;
drop policy if exists clients_all_access on public.clients;
drop policy if exists products_all_access on public.products;
drop policy if exists initial_stocks_all_access on public.initial_stocks;
drop policy if exists replenishments_all_access on public.replenishments;
drop policy if exists sales_all_access on public.sales;
drop policy if exists sale_items_all_access on public.sale_items;
drop policy if exists stock_movements_all_access on public.stock_movements;
drop policy if exists audit_logs_all_access on public.audit_logs;
drop policy if exists invoice_sequences_all_access on public.invoice_sequences;
drop policy if exists inventory_cycles_all_access on public.inventory_cycles;

create policy users_read_all on public.users
for select
to authenticated
using (true);

create policy clients_all_access on public.clients
for all
to public
using (true)
with check (true);

create policy products_all_access on public.products
for all
to public
using (true)
with check (true);

create policy initial_stocks_all_access on public.initial_stocks
for all
to public
using (true)
with check (true);

create policy replenishments_all_access on public.replenishments
for all
to public
using (true)
with check (true);

create policy sales_all_access on public.sales
for all
to public
using (true)
with check (true);

create policy sale_items_all_access on public.sale_items
for all
to public
using (true)
with check (true);

create policy stock_movements_all_access on public.stock_movements
for all
to public
using (true)
with check (true);

create policy audit_logs_all_access on public.audit_logs
for all
to public
using (true)
with check (true);

create policy invoice_sequences_all_access on public.invoice_sequences
for all
to public
using (true)
with check (true);

create policy inventory_cycles_all_access on public.inventory_cycles
for all
to public
using (true)
with check (true);
