create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  detail text not null,
  nature text not null,
  amount numeric(12, 2) not null,
  expense_date timestamptz not null default timezone('utc', now()),
  user_id bigint references public.users(id) on delete set null,
  approved_by text not null,
  purpose text not null
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null default 'Service general',
  unit_price numeric(12, 2) not null,
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sale_service_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  quantity integer not null,
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2) not null
);

alter table public.expenses enable row level security;
alter table public.services enable row level security;
alter table public.sale_service_items enable row level security;

alter table public.users
add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;

alter table public.audit_logs
add column if not exists actor_name text;

alter table public.audit_logs
add column if not exists actor_username text;

alter table public.audit_logs
add column if not exists source_device text;

alter table public.audit_logs
add column if not exists source_platform text;

alter table public.initial_stocks
add column if not exists cycle_id bigint;

alter table public.replenishments
add column if not exists cycle_id bigint;

alter table public.sales
add column if not exists cycle_id bigint;

alter table public.stock_movements
add column if not exists cycle_id bigint;

create table if not exists public.inventory_cycles (
  id bigint generated by default as identity primary key,
  label text not null,
  started_at timestamptz not null default timezone('utc', now()),
  user_id bigint references public.users(id) on delete set null
);

alter table public.inventory_cycles enable row level security;

insert into public.inventory_cycles (label)
select 'Cycle 1'
where not exists (select 1 from public.inventory_cycles);

update public.initial_stocks set cycle_id = coalesce(cycle_id, 1) where cycle_id is null;
update public.replenishments set cycle_id = coalesce(cycle_id, 1) where cycle_id is null;
update public.sales set cycle_id = coalesce(cycle_id, 1) where cycle_id is null;
update public.stock_movements set cycle_id = coalesce(cycle_id, 1) where cycle_id is null;

drop view if exists public.current_stock_view;

create view public.current_stock_view as
select
  p.id as product_id,
  p.name as product_name,
  coalesce(sum(case when sm.quantity > 0 then sm.quantity else 0 end), 0) as quantity_in,
  coalesce(sum(case when sm.quantity < 0 then abs(sm.quantity) else 0 end), 0) as quantity_out,
  coalesce(sum(sm.quantity), 0) as current_stock,
  p.alert_threshold as alert_threshold
from public.products p
left join public.stock_movements sm
  on sm.product_id = p.id
 and sm.cycle_id = (select coalesce(max(ic.id), 1) from public.inventory_cycles ic)
group by p.id, p.name, p.alert_threshold;

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.users
  where auth_user_id = auth.uid()
    and active = true
  limit 1;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'Super admin', false);
$$;

create or replace function public.is_admin_role()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() in ('Super admin', 'Administrateur'), false);
$$;

create or replace function public.find_login_user(p_identifier text)
returns table (
  id bigint,
  email text,
  active boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select u.id, u.email, u.active
  from public.users u
  where lower(u.username) = lower(trim(p_identifier))
     or lower(coalesce(u.email, '')) = lower(trim(p_identifier))
  limit 1;
$$;

create or replace function public.link_authenticated_user(p_email text)
returns table (
  id bigint,
  auth_user_id uuid,
  full_name text,
  username text,
  email text,
  role text,
  active boolean,
  created_at timestamptz,
  last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.users
  set
    auth_user_id = auth.uid(),
    last_login_at = timezone('utc', now())
  where lower(coalesce(users.email, '')) = lower(trim(p_email))
    and users.active = true
    and (users.auth_user_id is null or users.auth_user_id = auth.uid());

  return query
  select u.id, u.auth_user_id, u.full_name, u.username, u.email, u.role, u.active, u.created_at, u.last_login_at
  from public.users u
  where u.auth_user_id = auth.uid()
  limit 1;
end;
$$;

create or replace function public.touch_last_login()
returns table (
  id bigint,
  auth_user_id uuid,
  full_name text,
  username text,
  email text,
  role text,
  active boolean,
  created_at timestamptz,
  last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
 begin
   update public.users
   set last_login_at = timezone('utc', now())
  where public.users.auth_user_id = auth.uid()
    and active = true;

  return query
  select u.id, u.auth_user_id, u.full_name, u.username, u.email, u.role, u.active, u.created_at, u.last_login_at
  from public.users u
  where u.auth_user_id = auth.uid()
  limit 1;
end;
$$;

create or replace function public.sync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), true);
  perform setval(pg_get_serial_sequence('public.clients', 'id'), coalesce((select max(id) from public.clients), 1), true);
  perform setval(pg_get_serial_sequence('public.expenses', 'id'), coalesce((select max(id) from public.expenses), 1), true);
  perform setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1), true);
  perform setval(pg_get_serial_sequence('public.services', 'id'), coalesce((select max(id) from public.services), 1), true);
  perform setval(pg_get_serial_sequence('public.initial_stocks', 'id'), coalesce((select max(id) from public.initial_stocks), 1), true);
  perform setval(pg_get_serial_sequence('public.replenishments', 'id'), coalesce((select max(id) from public.replenishments), 1), true);
  perform setval(pg_get_serial_sequence('public.sales', 'id'), coalesce((select max(id) from public.sales), 1), true);
  perform setval(pg_get_serial_sequence('public.sale_items', 'id'), coalesce((select max(id) from public.sale_items), 1), true);
  perform setval(pg_get_serial_sequence('public.sale_service_items', 'id'), coalesce((select max(id) from public.sale_service_items), 1), true);
  perform setval(pg_get_serial_sequence('public.stock_movements', 'id'), coalesce((select max(id) from public.stock_movements), 1), true);
  perform setval(pg_get_serial_sequence('public.audit_logs', 'id'), coalesce((select max(id) from public.audit_logs), 1), true);
  perform setval(pg_get_serial_sequence('public.inventory_cycles', 'id'), coalesce((select max(id) from public.inventory_cycles), 1), true);
end;
$$;

grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_super_admin() to authenticated;
grant execute on function public.is_admin_role() to authenticated;
grant execute on function public.find_login_user(text) to anon, authenticated;
grant execute on function public.link_authenticated_user(text) to authenticated;
grant execute on function public.touch_last_login() to authenticated;
grant execute on function public.sync_identity_sequences() to authenticated;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at
before update on public.services
for each row
execute function public.set_updated_at();

drop policy if exists users_read_all on public.users;
drop policy if exists clients_all_access on public.clients;
drop policy if exists expenses_all_access on public.expenses;
drop policy if exists products_all_access on public.products;
drop policy if exists services_all_access on public.services;
drop policy if exists initial_stocks_all_access on public.initial_stocks;
drop policy if exists replenishments_all_access on public.replenishments;
drop policy if exists sales_all_access on public.sales;
drop policy if exists sale_items_all_access on public.sale_items;
drop policy if exists sale_service_items_all_access on public.sale_service_items;
drop policy if exists stock_movements_all_access on public.stock_movements;
drop policy if exists audit_logs_all_access on public.audit_logs;
drop policy if exists invoice_sequences_all_access on public.invoice_sequences;
drop policy if exists inventory_cycles_all_access on public.inventory_cycles;

drop policy if exists users_select_policy on public.users;
drop policy if exists users_insert_policy on public.users;
drop policy if exists users_update_policy on public.users;
drop policy if exists users_delete_policy on public.users;
drop policy if exists clients_select_policy on public.clients;
drop policy if exists clients_write_policy on public.clients;
drop policy if exists expenses_select_policy on public.expenses;
drop policy if exists expenses_write_policy on public.expenses;
drop policy if exists products_select_policy on public.products;
drop policy if exists products_write_policy on public.products;
drop policy if exists services_select_policy on public.services;
drop policy if exists services_write_policy on public.services;
drop policy if exists initial_stocks_select_policy on public.initial_stocks;
drop policy if exists initial_stocks_write_policy on public.initial_stocks;
drop policy if exists replenishments_select_policy on public.replenishments;
drop policy if exists replenishments_write_policy on public.replenishments;
drop policy if exists sales_select_policy on public.sales;
drop policy if exists sales_write_policy on public.sales;
drop policy if exists sale_items_select_policy on public.sale_items;
drop policy if exists sale_items_write_policy on public.sale_items;
drop policy if exists sale_service_items_select_policy on public.sale_service_items;
drop policy if exists sale_service_items_write_policy on public.sale_service_items;
drop policy if exists stock_movements_select_policy on public.stock_movements;
drop policy if exists stock_movements_write_policy on public.stock_movements;
drop policy if exists audit_logs_select_policy on public.audit_logs;
drop policy if exists audit_logs_write_policy on public.audit_logs;
drop policy if exists invoice_sequences_select_policy on public.invoice_sequences;
drop policy if exists invoice_sequences_write_policy on public.invoice_sequences;
drop policy if exists inventory_cycles_select_policy on public.inventory_cycles;
drop policy if exists inventory_cycles_write_policy on public.inventory_cycles;

create policy users_select_policy on public.users
for select
to authenticated
using (public.is_super_admin() or auth_user_id = auth.uid());

create policy users_insert_policy on public.users
for insert
to authenticated
with check (public.is_super_admin());

create policy users_update_policy on public.users
for update
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

create policy users_delete_policy on public.users
for delete
to authenticated
using (public.is_super_admin());

create policy clients_select_policy on public.clients
for select
to authenticated
using (true);

create policy clients_write_policy on public.clients
for all
to authenticated
using (true)
with check (true);

create policy expenses_select_policy on public.expenses
for select
to authenticated
using (true);

create policy expenses_write_policy on public.expenses
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy products_select_policy on public.products
for select
to authenticated
using (true);

create policy products_write_policy on public.products
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy services_select_policy on public.services
for select
to authenticated
using (true);

create policy services_write_policy on public.services
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy initial_stocks_select_policy on public.initial_stocks
for select
to authenticated
using (true);

create policy initial_stocks_write_policy on public.initial_stocks
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy replenishments_select_policy on public.replenishments
for select
to authenticated
using (true);

create policy replenishments_write_policy on public.replenishments
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy sales_select_policy on public.sales
for select
to authenticated
using (true);

create policy sales_write_policy on public.sales
for all
to authenticated
using (true)
with check (true);

create policy sale_items_select_policy on public.sale_items
for select
to authenticated
using (true);

create policy sale_items_write_policy on public.sale_items
for all
to authenticated
using (true)
with check (true);

create policy sale_service_items_select_policy on public.sale_service_items
for select
to authenticated
using (true);

create policy sale_service_items_write_policy on public.sale_service_items
for all
to authenticated
using (true)
with check (true);

create policy stock_movements_select_policy on public.stock_movements
for select
to authenticated
using (true);

create policy stock_movements_write_policy on public.stock_movements
for all
to authenticated
using (true)
with check (true);

create policy audit_logs_select_policy on public.audit_logs
for select
to authenticated
using (public.is_super_admin());

create policy audit_logs_write_policy on public.audit_logs
for all
to authenticated
using (true)
with check (true);

create policy invoice_sequences_select_policy on public.invoice_sequences
for select
to authenticated
using (true);

create policy invoice_sequences_write_policy on public.invoice_sequences
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());

create policy inventory_cycles_select_policy on public.inventory_cycles
for select
to authenticated
using (true);

create policy inventory_cycles_write_policy on public.inventory_cycles
for all
to authenticated
using (public.is_admin_role())
with check (public.is_admin_role());
